--- makefile	2013-07-24 19:00:27.498952532 -0500
+++ makefile.new	2013-07-24 19:02:02.391141388 -0500
@@ -1,10 +1,10 @@
 # $* is prefix shared by target and dependent;  $@ is name of target file
-CFLAGS = -c -O3 -Ibamtools/src
+CFLAGS = -c -O3 -I/usr/include/bamtools
 OBJS= repeatseq.o structures.o CLParse.o
 NAME= repeatseq
 
 $(NAME): $(OBJS)
-	g++ -o $@ $(OBJS) fastahack/Fasta.cpp fastahack/split.cpp -lpthread -lbamtools -Lbamtools/lib 
+	g++ -o $@ $(OBJS) fastahack/Fasta.cpp fastahack/split.cpp -lpthread -lbamtools 
 
 # Suffix rules: tell how to  take file with first suffix and make it into
 #	file with second suffix
